name: const_date_time_range
description: A drop-in replacement for Dart's DateTimRange class with const constructors.
version: 0.0.1
repository: https://github.com/westy92/const-date-time-range
issue_tracker: https://github.com/westy92/const-date-tim-range/issues
funding:
  - https://github.com/sponsors/westy92

environment:
  sdk: '>=2.18.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  const_date_time: ^1.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.16.0
  flutter_test:
    sdk: flutter

topics:
  - date
  - time
  - date-time
  - const
  - util
